// Generated by https://quicktype.io

export interface IResProducto {
  total:     number;
  productos: IProducto[];
}

export interface IProducto {
  _id?:    string;
  nombre: string;
  estado?: boolean;
  precio: number;
  costo:  number;
  minimo: number;
  stock:  number;
  __v?:    number;
}
